---
- name: Download distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    dest: "~/vector-{{ vector_version }}.tar.gz"
    mode: +rw
- name: Create distrib directory
  ansible.builtin.file:
    path: "~/vector"
    state: directory
    mode: "u+rwx,g+r,o+r"
- name: Unpack vector distrib by unarchive
  ansible.builtin.unarchive:
    src: "~/vector-{{ vector_version }}.tar.gz"
    remote_src: true
    dest: "~/vector"
    extra_opts: ["--strip-components=2"]
  register: unpack_res
- name: Install vector executable
  become: true
  ansible.builtin.copy:
    src: "{{ unpack_res['dest'] }}/bin/vector"
    remote_src: true
    dest: "/usr/bin/vector"
    mode: +x
  notify: Start vector service
- name: Create vector directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
  loop:
    - "{{ vector_datadir }}"
    - "/etc/vector"
- name: Create test directory
  ansible.builtin.file:
    path: "{{ vector_test_dir }}"
    state: directory
    mode: "u+rwx,g+rx,o+r"
- name: Install vector configuration
  become: true
  ansible.builtin.template:
    src: vector.toml.j2
    dest: "{{ vector_config }}"
    mode: "0644"
  notify: Start vector service
- name: Install vector service file
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: "/usr/lib/systemd/system/vector.service"
    mode: "0644"
- name: Enable vector service
  become: true
  ansible.builtin.service:
    name: "vector"
    enabled: true
    state: started
...
